### ISSUE TITLE
Can we do pull requests for custom codes to this repository?

### ISSUE THREAD

**Issue by vik-y** [openbangalore/bmtc#2]
hey, 

First of all thanks a lot for this beautiful dataset. It was much needed. I have written some python functions which use this dataset to pull relevant information from mybmtc site. For example, given a bus no, there's a function which returns the list of all bus stops and their gps coordinates. I'm writing more libraries for pulling relevant data. I wanted to know that do you accept those pull requests? And to which folder should I add my files if you do accept.

**Comment by thejeshgn** [comment]
@vik-y I was on a long drive across India. Hence didnt see this earlier. I do accept pull requests. In fact  more than welcome :)
\

**Comment by vik-y** [comment]
I hope you enjoyed your long drive. Must have been an amazing experience. :+1: 

Thanks for accepting the pull request.

**Comment by thejeshgn** [comment]
On 14 July 2015 at 10:00, Vikas Yadav <notifications@github.com> wrote:

> Must have been an amazing experience.


It was great. Thanks.


Thej
--
Thejesh GN *⏚* ತೇಜೇಶ್ ಜಿ.ಎನ್
http://thejeshgn.com
GPG ID :  0xBFFC8DD3C06DD6B0
